<?php
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_hsw-directory-listings',
		'title' => 'HSW Directory Listings',
		'fields' => array (
			array (
				'key' => 'field_5b293a5f68a42',
				'label' => 'Short Description',
				'name' => 'short_description',
				'type' => 'text',
				'instructions' => 'A short description of the listing, used throughout the theme,',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b29398068a3f',
				'label' => 'Website URL',
				'name' => 'website',
				'type' => 'text',
				'instructions' => 'The full website URL this listing will link to, e.g. https://example.com',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b29399b68a40',
				'label' => 'Twitter URL',
				'name' => 'twitter_url',
				'type' => 'text',
				'instructions' => 'The full Twitter URL this listing.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b2939b968a41',
				'label' => 'Facebook URL',
				'name' => 'facebook_url',
				'type' => 'text',
				'instructions' => 'The full Facebook URL this listing.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b2952aaa2184',
				'label' => 'Google URL',
				'name' => 'google_url',
				'type' => 'text',
				'instructions' => 'The full Google+ URL for this listing.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b2952c9a2185',
				'label' => 'LinkedIn URL',
				'name' => 'linkedin_url',
				'type' => 'text',
				'instructions' => 'The full LinkedIn URL for this listing.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b2952e8a2186',
				'label' => 'Pinterest URL',
				'name' => 'pinterest_url',
				'type' => 'text',
				'instructions' => 'The full Pinterest URL for this listing.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b2952f2a2187',
				'label' => 'Instagram URL',
				'name' => 'instagram_url',
				'type' => 'text',
				'instructions' => 'The full Instagram URL for this listing.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b293a7a68a43',
				'label' => 'Phone Number',
				'name' => 'phone_number',
				'type' => 'text',
				'instructions' => 'Phone number to display for this listing.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b366e05291ec',
				'label' => 'Address',
				'name' => 'address',
				'type' => 'text',
				'instructions' => 'Address to display for this listing.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b2acd011bd23',
				'label' => 'Email Address',
				'name' => 'email_address',
				'type' => 'email',
				'instructions' => 'Email address for the listing contact form.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array (
				'key' => 'field_5b293b037460a',
				'label' => 'Is Featured',
				'name' => 'is_featured',
				'type' => 'true_false',
				'instructions' => 'Mark this listing as featured.',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_5b2a1b030e69e',
				'label' => 'Key Value Pairs',
				'name' => 'key_value_pairs',
				'type' => 'textarea',
				'instructions' => 'Add key value pairs to this listing, separated by a colon e.g. 
				<br><br>
				Parking : Yes<br>
				Disabled Access : Yes<br>
				Happy Hour : 10pm - 2am',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5b3af27519714',
				'label' => 'Location',
				'name' => 'location',
				'type' => 'mapbox',
				'address' => 'Default Address',
				'lat' => 55.869058,
				'lng' => -2.091068,
			),
		),
'location' => array (
	array (
		array (
			'param' => 'post_type',
			'operator' => '==',
			'value' => 'hsw_dir_listing',
			'order_no' => 0,
			'group_no' => 0,
		),
	),
),
'options' => array (
	'position' => 'normal',
	'layout' => 'default',
	'hide_on_screen' => array (
	),
),
'menu_order' => 0,
));
}
